### ISSUE TITLE
"Editor"- Error

### ISSUE THREAD

**Issue by DarKRealm79** [LtdJorge/TextureManipulationUtilities#1]
Based on the error-message I got and the following article it's necessary to rename the namespace in all Editor-Scripts.
https://forum.unity.com/threads/error-while-using-an-editor-namespace-when-assets-use-editor-as-a-type-unityeditor-editor.1103488/

for example like: 
namespace TextureManipulationUtilities.Editor{}

using TextureManipulationUtilities.Editor.Util;

**Comment by LtdJorge** [comment]
Sorry that I didn't respond. I was transitioning to a Linux desktop. I will install Unity and let you know.

What version of Unity are you using?

**Comment by DarKRealm79** [comment]
Hi there,

No worry, I could fix the problem for my project. I'm using Unity 2019.4
but as I wrote already, it's just a namspace error if you are already using
some other scripts in your project. It's easier to rename it generally so
people don't get this error in any situation.

Best regards
Gerald

Jorge López Tello ***@***.***> schrieb am Mi., 22. Feb. 2023,
13:48:

**Comment by LtdJorge** [comment]
Hi @DarKRealm79, I just pushed a little change to fix this. It took me a long time to get Unity perfectly working on Linux with Wayland. So much that at some point I even forgot about it.

You said that you already implemented it for yourself, now you can clone from the original instead of needing a patched version. By the way, just in case you didn't notice, you can use this project by cloning into your assets folder, or better yet, by specifying the repo to the Unity package manager. UPM does the work for you.
